### ISSUE TITLE
Unable to connect to graphql for Complete App with GraphQL, Node.js, MongoDB and React.js

### ISSUE THREAD

**Issue by LorelaiG** [LorelaiG/GraphQLapp#1]
I get this error message when i do npm start:
> event-booking@1.0.0 start C:\Users\Lenovo\Desktop\simpleWebsites\event-booking
> nodemon app.js

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
(node:7984) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
{ MongoError: bad auth Authentication failed.
    at _authenticateSingleConnection (C:\Users\Lenovo\Desktop\simpleWebsites\event-booking\node_modules\mongodb-core\lib\auth\auth_provider.js:46:25)
    at sendAuthCommand (C:\Users\Lenovo\Desktop\simpleWebsites\event-booking\node_modules\mongodb-core\lib\auth\scram.js:215:18)
    at Connection.messageHandler (C:\Users\Lenovo\Desktop\simpleWebsites\event-booking\node_modules\mongodb-core\lib\connection\connect.js:334:5)
    at Connection.emit (events.js:182:13)
    at processMessage (C:\Users\Lenovo\Desktop\simpleWebsites\event-booking\node_modules\mongodb-core\lib\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\Users\Lenovo\Desktop\simpleWebsites\event-booking\node_modules\mongodb-core\lib\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  ok: 0,
  errmsg: 'bad auth Authentication failed.',
  code: 8000,
  codeName: 'AtlasError',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
[nodemon] clean exit - waiting for changes before restart

According to the mogoose docs, this is the way to write the code:
 /*mongoose.connect(uri, { useNewUrlParser: true });
mongoose.createConnection(uri, { useNewUrlParser: true }); */

but i cant figure out how t modify my current code to fit the correct one;
mongoose
  .connect(
    `mongodb+srv://${process.env.MONGO_USER}:${
      process.env.MONGO_PASSWORD
    }@cluster0-ffdhh.azure.mongodb.net/${
      process.env.MONGO_DB
    }?retryWrites=true&w=majority`
  )

**Comment by LorelaiG** [comment]
![parser](https://user-images.githubusercontent.com/47509482/59053883-ba143500-8892-11e9-8589-757b214fbdf4.PNG)
